name: Deploy to Vercel Preview for PRs
on:
  pull_request:
env:
  PREVIEW_URL: "aeswibon-preview-${{ github.event.pull_request.head.ref }}.vercel.app"
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Commenting on Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deploying to Vercel Preview at $PREVIEW_URL'
            })
  preview:
    uses: ./.github/workflows/preview.yaml
