name: Deploy to Vercel Preview
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
env:
  PREVIEW_URL: "aeswibon-preview.vercel.app"
jobs:
  comment:
    if: ${{ github.event_name }} == 'pull_request' && ${{ github.event.action }} == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Update Preview URL
        run: echo "https://aeswibon-preview-{{ github.event.pull_request.head.ref }},vercel.app" >> $PREVIEW_URL
      - name: Commenting on Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deploying to Vercel Preview at $PREVIEW_URL'
            })
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build the project artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Preview
        run: |
          OUTPUT=$(du --inodes -d 5 .vercel/output)
          echo "$OUTPUT"
          LAST=$(echo "$OUTPUT" | tail -n 1)
          PERCENTAGE=$(echo "$LAST" | awk 'BEGIN {maxtotal=15000} { printf "%.2f%%", ($1/maxtotal*100) }')
          echo "Vercel file usage percentage" >> $GITHUB_STEP_SUMMARY
          echo "$PERCENTAGE" >> $GITHUB_STEP_SUMMARY
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          vercel alias --token ${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` $PREVIEW_URL
